kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ''
  volumeMode: Filesystem
  volumeName: wordpress-pv
