apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: /data/mysql
    server: k8sr-master.home.lcl
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
